spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3307/test
      username: root   # 只读账户
      password:
      driver-class-name: com.mysql.jdbc.Driver
