server:
  port: 8089

spring:
  application:
    name: dubbo-study-consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/transaction_b?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.transformers.consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181

hmily:
  support:
    rpc:
      annotation: true

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: debug
    org.dromara.hmily.demo.bonuspoint: debug
    org.dromara.hmily.demo.lottery: debug
    org.dromara.hmily.demo: debug
    io.netty: info
  file:
    path: "./logs"
